In [1]:
import numpy as np

1. 写出以矩阵A作为输入，输出L和U的代码。使用以下矩阵验证。
$$
(a)
\begin{bmatrix}
3 & 1 & 2 \\
6 & 3 & 4 \\
3 & 1 & 5 \\
\end{bmatrix}
\qquad
(b)
\begin{bmatrix}
4 & 2 & 0 \\
4 & 4 & 2 \\
2 & 2 & 3 \\
\end{bmatrix}
\qquad
(c)
\begin{bmatrix}
1 & -1 & 1 & 2 \\
0 & 2 & 1 & 0 \\
1 & 3 & 4 & 4 \\
0 & 2 & 1 & -1
\end{bmatrix}
$$

In [27]:
def LUFactorization(A_:np.ndarray, printOrNot=True, check=True):
    order = A_.shape[0]

    # Upper triangular matrix
    U = A_.copy()
    # Lower triangular matrix
    L = np.eye(order)

    # Elimination
    for col in range(order):
        if np.abs(A_[col][col]) < 0.00000001:
            print("Zero pivot encounterd. i=j=:", col)
            return None
        for row in range(col+1, order):
            mult = U[row][col]/U[col][col]
            L[row][col] = mult
            for k in range(col, order):
                U[row][k] -= mult*U[col][k]
    
    if printOrNot:
        print('L:\n', L)
        print('U:\n', U)

    if check:
        print('error:\n', np.abs(A_-L@U))

    return (L, U)

In [28]:
_, _ = LUFactorization(np.array([[3.,1,2],[6,3,4],[3,1,5]]))
_, _ = LUFactorization(np.array([[4.,2,0],[4,4,2],[2,2,3]]))
_, _ = LUFactorization(np.array([[1.,-1,1,2],[0,2,1,0],[1,3,4,4],[0,2,1,-1]]))

L:
 [[1. 0. 0.]
 [2. 1. 0.]
 [1. 0. 1.]]
U:
 [[3. 1. 2.]
 [0. 1. 0.]
 [0. 0. 3.]]
error:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
L:
 [[1.  0.  0. ]
 [1.  1.  0. ]
 [0.5 0.5 1. ]]
U:
 [[4. 2. 0.]
 [0. 2. 2.]
 [0. 0. 2.]]
error:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
L:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [1. 2. 1. 0.]
 [0. 1. 0. 1.]]
U:
 [[ 1. -1.  1.  2.]
 [ 0.  2.  1.  0.]
 [ 0.  0.  1.  2.]
 [ 0.  0.  0. -1.]]
error:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


2. 使用LU分解和两部回代解下列方程组：
$$
(a)
\begin{bmatrix}
3 & 1 & 2 \\
6 & 3 & 4 \\
3 & 1 & 5 \\
\end{bmatrix}
\begin{bmatrix}
x_1 \\
x_2 \\
x_3 \\
\end{bmatrix}
=
\begin{bmatrix}
0 \\
1 \\
3 \\
\end{bmatrix}
\,\\
\,\\
(b)
\begin{bmatrix}
4 & 2 & 0 \\
4 & 4 & 2 \\
2 & 2 & 3 \\
\end{bmatrix}
\begin{bmatrix}
x_1 \\
x_2 \\
x_3 \\
\end{bmatrix}
=
\begin{bmatrix}
2 \\
4 \\
6 \\
\end{bmatrix}
$$

In [39]:
def TwoStepBackSubstitution(A:np.ndarray, b_:np.ndarray, check=True):
    L, U = LUFactorization(A, False, False)
    b = b_.copy()
    order = A.shape[0]

    # Ax=b becomes LUx=b
    # Let c=Ux,
    # then evaluate c through Lc=b
    # Finally evaluate x through Ux=c

    # Solve Lc=b
    c = np.zeros(order)
    for row in range(order):
        for col in range(row):
            b[row] -= L[row][col]*c[col]
        c[row] = b[row]

    # Solve Ux=c
    x = np.zeros(order)
    for row in range(order)[::-1]:
        for col in range(row+1, order):
            c[row] -= U[row][col]*x[col]
        x[row] = c[row]/U[row][row]
    print('x:\n', x)

    if check:
        print('error: ', np.abs(b_-A@x))
    print()

In [41]:
TwoStepBackSubstitution(np.array([[3,1,2],[6,3,4],[3,1,5]]), np.array([0,1,3]))
TwoStepBackSubstitution(np.array([[4,2,0],[4,4,2],[2,2,3]]), np.array([2,4,6]))

x:
 [-1.  1.  1.]
error:  [0. 0. 0.]

x:
 [ 1. -1.  2.]
error:  [0. 0. 0.]

