In [79]:
import numpy as np

In [80]:
def NaiveGaussinElimination(M_:np.ndarray, b_:np.ndarray, check=False):
    M = M_.copy()
    b = b_.copy()
    if M.shape[0] != M.shape[1]:
        print("M is not a square matrix.")
        return None

    order = M.shape[0]

    # Elimination
    for col in range(order):
        if np.abs(M_[col][col]) < 0.00000001:
            print("Zero pivot encounterd. i=j=:", col)
            return None
        for row in range(col+1, order):
            mult = M[row][col]/M[col][col]
            for k in range(col, order):
                M[row][k] -= mult*M[col][k]
            b[row] -= mult*b[col]
        # print(M, '\n')
    # print(M, '\n')
    # print(b, '\n')

    # Back substitution
    res = np.zeros(order)
    for row in range(order)[::-1]:
        for col in range(row+1, order):
            b[row] -= M[row][col]*res[col]
        res[row] = b[row]/M[row][row]
    
    print(res)

    if check:
        for row in range(order):
            left = 0
            for col in range(order):
                left += M_[row][col]*res[col]
            print(row, 'error: ', np.abs(b_[row]-left))

1. 解以下方程组：
$$
\begin{aligned}
&\begin{cases}
2x-2y-z=-2 \\
4x+y-2z=1 \\
-2x+y-z=-3 \\
\end{cases}
\\
\\
&\begin{cases}
x+2y-z=2 \\
3y+z=4 \\
2x-y+z=2 \\
\end{cases}
\\
\\
&\begin{cases}
2x+y-4z=-7 \\
x-y+z=-2 \\
-x+3y-2z=6 \\
\end{cases}
\end{aligned}
$$

In [81]:
NaiveGaussinElimination(
    np.array([[2,-2,-1], [4,1,-2], [-2,1,-1]]),
    np.array([-2,1,-3]),
    True
)
NaiveGaussinElimination(
    np.array([[1,2,-1], [0,3,1], [2,-1,1]]),
    np.array([2,4,2]),
    True
)
NaiveGaussinElimination(
    np.array([[2.,1,-4], [1,-1,1], [-1,3,-2]]),
    np.array([-7.,-2,6]),
    True
)

[1. 1. 2.]
0 error:  0.0
1 error:  0.0
2 error:  0.0
[1. 1. 1.]
0 error:  0.0
1 error:  0.0
2 error:  0.0
[-1.  3.  2.]
0 error:  0.0
1 error:  0.0
2 error:  0.0


2. H为n*n的希尔伯特矩阵，其中 $a_{ij}=1/(i+j-1)$。求解 $Hx=b$，b为元素全为1的向量，其中
$$
\begin{aligned}
(a)&\;n=2 \\
(b)&\;n=5 \\
(c)&\;n=10 \\
\end{aligned}
$$

In [82]:
def GenerateHilbertMatrix(n):
    return np.array([
        [
            1/(col+row-1) for col in range(1, n+1)
        ] for row in range(1, n+1)
    ])

h = GenerateHilbertMatrix(3)
print(h)

[[1.         0.5        0.33333333]
 [0.5        0.33333333 0.25      ]
 [0.33333333 0.25       0.2       ]]


In [83]:
NaiveGaussinElimination(GenerateHilbertMatrix(2), np.ones(2), True)
NaiveGaussinElimination(GenerateHilbertMatrix(5), np.ones(5), True)
NaiveGaussinElimination(GenerateHilbertMatrix(10), np.ones(10), True)

[-2.  6.]
0 error:  0.0
1 error:  0.0
[    5.  -120.   630. -1120.   630.]
0 error:  0.0
1 error:  2.842170943040401e-14
2 error:  1.4210854715202004e-14
3 error:  0.0
4 error:  0.0
[-9.99736482e+00  9.89771861e+02 -2.37551338e+04  2.40195714e+05
 -1.26104860e+06  3.78319850e+06 -6.72576549e+06  7.00035724e+06
 -3.93773542e+06  9.23673408e+05]
0 error:  5.820766091346741e-11
1 error:  7.275957614183426e-11
2 error:  4.3655745685100555e-11
3 error:  2.9103830456733704e-11
4 error:  4.3655745685100555e-11
5 error:  8.003553375601768e-11
6 error:  4.3655745685100555e-11
7 error:  2.1827872842550278e-11
8 error:  7.275957614183426e-12
9 error:  5.820766091346741e-11
